export const companyConstants = {
    SWITCH_SELECTION: 'SWITCH_SELECTION',

    GETALL_REQUEST: 'COMPANY_GETALL_REQUEST',
    GETALL_SUCCESS: 'COMPANY_GETALL_SUCCESS',
    GETALL_FAILURE: 'COMPANY_GETALL_FAILURE',

    GET_REQUEST: 'COMPANY_GET_REQUEST',
    GET_SUCCESS: 'COMPANY_GET_SUCCESS',
    GET_FAILURE: 'COMPANY_GET_FAILURE',

    UPDATE_REQUEST: 'COMPANY_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMPANY_UPDATE_FAILURE',

    DELETE_REQUEST: 'COMPANY_DELETE_REQUEST',
    DELETE_SUCCESS: 'COMPANY_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMPANY_DELETE_FAILURE'
};

export const GET_REQUEST = 'COMPANY_GET_REQUEST';
export const GET_SUCCESS = 'COMPANY_GET_SUCCESS';
export const GET_FAILURE = 'COMPANY_GET_FAILURE';

export const UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'COMPANY_UPDATE_FAILURE';

export const SWITCH_SELECTION = 'SWITCH_SELECTION';

export const GETALL_REQUEST = 'COMPANY_GETALL_REQUEST';
export const GETALL_SUCCESS = 'COMPANY_GETALL_SUCCESS';
export const GETALL_FAILURE = 'COMPANY_GETALL_FAILURE';

export const DELETE_REQUEST = 'COMPANY_DELETE_REQUEST';
export const DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const DELETE_FAILURE = 'COMPANY_DELETE_FAILURE';

export type GET_REQUEST = typeof GET_REQUEST ;
export type GET_SUCCESS = typeof GET_SUCCESS ;
export type GET_FAILURE = typeof GET_FAILURE ;

export type UPDATE_REQUEST = typeof UPDATE_REQUEST ;
export type UPDATE_SUCCESS = typeof UPDATE_SUCCESS ;
export type UPDATE_FAILURE = typeof UPDATE_FAILURE ;

export type SWITCH_SELECTION = typeof SWITCH_SELECTION ;

export type GETALL_REQUEST = typeof GETALL_REQUEST ;
export type GETALL_SUCCESS = typeof GETALL_SUCCESS ;
export type GETALL_FAILURE = typeof GETALL_FAILURE ;

export type DELETE_REQUEST = typeof DELETE_REQUEST ;
export type DELETE_SUCCESS = typeof DELETE_SUCCESS ;
export type DELETE_FAILURE = typeof DELETE_FAILURE;
