export const deliveryConstants = {
    ADD_DELIVERY_REQUEST: 'ADD_DELIVERY_REQUEST',
    ADD_DELIVERY_SUCCESS: 'ADD_DELIVERY_SUCCESS',
    ADD_DELIVERY_FAILURE: 'ADD_DELIVERY_FAILURE',

    UPDATE_DELIVERY_REQUEST: 'UPDATE_DELIVERY_REQUEST',
    UPDATE_DELIVERY_SUCCESS: 'UPDATE_DELIVERY_SUCCESS',
    UPDATE_DELIVERY_FAILURE: 'UPDATE_DELIVERY_FAILURE',

    DELETE_DELIVERY_REQUEST: 'DELETE_DELIVERY_REQUEST',
    DELETE_DELIVERY_SUCCESS: 'DELETE_DELIVERY_SUCCESS',
    DELETE_DELIVERY_FAILURE: 'DELETE_DELIVERY_FAILURE',
};

export const UPDATE_DELIVERY_REQUEST = 'UPDATE_DELIVERY_REQUEST';
export const UPDATE_DELIVERY_SUCCESS = 'UPDATE_DELIVERY_SUCCESS';
export const UPDATE_DELIVERY_FAILURE = 'UPDATE_DELIVERY_FAILURE';

export const DELETE_DELIVERY_REQUEST = 'DELETE_DELIVERY_REQUEST';
export const DELETE_DELIVERY_SUCCESS = 'DELETE_DELIVERY_SUCCESS';
export const DELETE_DELIVERY_FAILURE = 'DELETE_DELIVERY_FAILURE';

export const ADD_DELIVERY_REQUEST = 'ADD_DELIVERY_REQUEST';
export const ADD_DELIVERY_SUCCESS = 'ADD_DELIVERY_SUCCESS';
export const ADD_DELIVERY_FAILURE = 'ADD_DELIVERY_FAILURE';

export type UPDATE_DELIVERY_REQUEST = typeof UPDATE_DELIVERY_REQUEST ;
export type UPDATE_DELIVERY_SUCCESS = typeof UPDATE_DELIVERY_SUCCESS ;
export type UPDATE_DELIVERY_FAILURE = typeof UPDATE_DELIVERY_FAILURE ;

export type DELETE_DELIVERY_REQUEST = typeof DELETE_DELIVERY_REQUEST ;
export type DELETE_DELIVERY_SUCCESS = typeof DELETE_DELIVERY_SUCCESS ;
export type DELETE_DELIVERY_FAILURE = typeof DELETE_DELIVERY_FAILURE ;

export type ADD_DELIVERY_REQUEST = typeof ADD_DELIVERY_REQUEST ;
export type ADD_DELIVERY_SUCCESS = typeof ADD_DELIVERY_SUCCESS ;
export type ADD_DELIVERY_FAILURE = typeof ADD_DELIVERY_FAILURE ;
