export const messageConstants = {
    GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',

    GET_USERSFORMESSAGE_REQUEST: 'GET_USERSFORMESSAGE_REQUEST',
    GET_USERSFORMESSAGE_SUCCESS: 'GET_USERSFORMESSAGE_SUCCESS',
    GET_USERSFORMESSAGE_FAILURE: 'GET_USERSFORMESSAGE_FAILURE',

    SEND_MESSAGES_REQUEST: 'SEND_MESSAGES_REQUEST',
    SEND_MESSAGES_SUCCESS: 'SEND_MESSAGES_SUCCESS',
    SEND_MESSAGES_FAILURE: 'SEND_MESSAGES_FAILURE',

};

export type GET_MESSAGES_REQUEST = typeof messageConstants.GET_MESSAGES_REQUEST;
export type GET_MESSAGES_SUCCESS = typeof messageConstants.GET_MESSAGES_SUCCESS;
export type GET_MESSAGES_FAILURE = typeof messageConstants.GET_MESSAGES_FAILURE;

export type GET_USERSFORMESSAGE_REQUEST = typeof messageConstants.GET_USERSFORMESSAGE_REQUEST;
export type GET_USERSFORMESSAGE_SUCCESS = typeof messageConstants.GET_USERSFORMESSAGE_SUCCESS;
export type GET_USERSFORMESSAGE_FAILURE = typeof messageConstants.GET_USERSFORMESSAGE_FAILURE;

export type SEND_MESSAGES_REQUEST = typeof messageConstants.SEND_MESSAGES_REQUEST;
export type SEND_MESSAGES_SUCCESS = typeof messageConstants.SEND_MESSAGES_SUCCESS;
export type SEND_MESSAGES_FAILURE = typeof messageConstants.SEND_MESSAGES_FAILURE;
