export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    AUTH_FAILURE: 'AUTH_FAILURE',
    AUTH_SUCCESS: 'AUTH_SUCCESS',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    RESET_PASSWORD_REQUEST: 'USERS_RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'USERS_RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'USERS_RESET_PASSWORD_FAILURE',

    UPDATE_PASSWORD_REQUEST: 'USERS_UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'USERS_UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'USERS_UPDATE_PASSWORD_FAILURE',

    SAVE_PASSWORD_REQUEST: 'USERS_SAVE_PASSWORD_REQUEST',
    SAVE_PASSWORD_SUCCESS: 'USERS_SAVE_PASSWORD_SUCCESS',
    SAVE_PASSWORD_FAILURE: 'USERS_SAVE_PASSWORD_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETONE_REQUEST: 'USERS_GETONE_REQUEST',
    GETONE_SUCCESS: 'USERS_GETONE_SUCCESS',
    GETONE_FAILURE: 'USERS_GETONE_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    COWORKER_UPDATE_REQUEST: 'COWORKER_UPDATE_REQUEST',
    COWORKER_UPDATE_SUCCESS: 'COWORKER_UPDATE_SUCCESS',
    COWORKER_UPDATE_FAILURE: 'COWORKER_UPDATE_FAILURE',

    USERDATA_UPDATE_REQUEST: 'USERDATA_UPDATE_REQUEST',
    USERDATA_UPDATE_SUCCESS: 'USERDATA_UPDATE_SUCCESS',
    USERDATA_UPDATE_FAILURE: 'USERDATA_UPDATE_FAILURE',

    COWORKER_ADD_REQUEST: 'COWORKER_ADD_REQUEST',
    COWORKER_ADD_SUCCESS: 'COWORKER_ADD_SUCCESS',
    COWORKER_ADD_FAILURE: 'COWORKER_ADD_FAILURE',

    COWORKER_UNPIN_REQUEST: 'COWORKER_UNPIN_REQUEST',
    COWORKER_UNPIN_SUCCESS: 'COWORKER_UNPIN_SUCCESS',
    COWORKER_UNPIN_FAILURE: 'COWORKER_UNPIN_FAILURE',

    POSUSERS_GET_REQUEST: 'POSUSERS_GET_REQUEST',
    POSUSERS_GET_SUCCESS: 'POSUSERS_GET_SUCCESS',
    POSUSERS_GET_FAILURE: 'POSUSERS_GET_FAILURE',
};

export const LOGOUT = 'USERS_LOGOUT';

export const COWORKER_UPDATE_REQUEST = 'COWORKER_UPDATE_REQUEST';
export const COWORKER_UPDATE_SUCCESS = 'COWORKER_UPDATE_SUCCESS';
export const COWORKER_UPDATE_FAILURE = 'COWORKER_UPDATE_FAILURE';

export const USERDATA_UPDATE_REQUEST = 'USERDATA_UPDATE_REQUEST';
export const USERDATA_UPDATE_SUCCESS = 'USERDATA_UPDATE_SUCCESS';
export const USERDATA_UPDATE_FAILURE = 'USERDATA_UPDATE_FAILURE';

export const COWORKER_ADD_REQUEST = 'COWORKER_ADD_REQUEST';
export const COWORKER_ADD_SUCCESS = 'COWORKER_ADD_SUCCESS';
export const COWORKER_ADD_FAILURE = 'COWORKER_ADD_FAILURE';

export const COWORKER_UNPIN_REQUEST = 'COWORKER_UNPIN_REQUEST';
export const COWORKER_UNPIN_SUCCESS = 'COWORKER_UNPIN_SUCCESS';
export const COWORKER_UNPIN_FAILURE = 'COWORKER_UNPIN_FAILURE';

export const POSUSERS_GET_REQUEST = 'POSUSERS_GET_REQUEST';
export const POSUSERS_GET_SUCCESS = 'POSUSERS_GET_SUCCESS';
export const POSUSERS_GET_FAILURE = 'POSUSERS_GET_FAILURE';

export type LOGOUT = typeof LOGOUT ;

export type COWORKER_UPDATE_REQUEST = typeof COWORKER_UPDATE_REQUEST ;
export type COWORKER_UPDATE_SUCCESS = typeof COWORKER_UPDATE_SUCCESS ;
export type COWORKER_UPDATE_FAILURE = typeof COWORKER_UPDATE_FAILURE;

export type USERDATA_UPDATE_REQUEST = typeof USERDATA_UPDATE_REQUEST ;
export type USERDATA_UPDATE_SUCCESS = typeof USERDATA_UPDATE_SUCCESS ;
export type USERDATA_UPDATE_FAILURE = typeof USERDATA_UPDATE_FAILURE;

export type COWORKER_ADD_REQUEST = typeof COWORKER_ADD_REQUEST ;
export type COWORKER_ADD_SUCCESS = typeof COWORKER_ADD_SUCCESS ;
export type COWORKER_ADD_FAILURE = typeof COWORKER_ADD_FAILURE;

export type COWORKER_UNPIN_REQUEST = typeof COWORKER_UNPIN_REQUEST ;
export type COWORKER_UNPIN_SUCCESS = typeof COWORKER_UNPIN_SUCCESS ;
export type COWORKER_UNPIN_FAILURE = typeof COWORKER_UNPIN_FAILURE;

export type POSUSERS_GET_REQUEST = typeof POSUSERS_GET_REQUEST ;
export type POSUSERS_GET_SUCCESS = typeof POSUSERS_GET_SUCCESS ;
export type POSUSERS_GET_FAILURE = typeof POSUSERS_GET_FAILURE;
